#!/usr/bin/env bash

set -e
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd .. && pwd)"

# This script uses Docker to build a fat jar for vapord.

IMAGE=openjdk:8-jdk-alpine
SBT_VERSION=1.1.6

docker build --pull -t build-vapord - <<EOT
FROM $IMAGE

RUN \
  apk add --no-cache bash git && \
  mkdir -p /opt && \
  wget -q -O - https://sbt-downloads.cdnedge.bluemix.net/releases/v${SBT_VERSION}/sbt-${SBT_VERSION}.tgz | \
  gunzip | \
  tar -x -C /opt

ENV PATH="/opt/sbt/bin:\${PATH}"

RUN adduser -D build -s $UID
USER build:build
WORKDIR /home/build

CMD ["/bin/bash"]
EOT

rm -rf "$PWD/target/build"
rsync -r --exclude=target . target/build
mkdir -p "$HOME/.cache/appalachian/vapord/build"
mkdir -p "$PWD/target/build"

docker run -i \
  -v "$HOME/.cache/appalachian/vapord/build:/home/build" \
  -v "$PWD/target/build:/home/build/vapord" build-vapord << EOT

set -e
cd vapord
sbt clean assembly
EOT

find target/build/target/scala-*/vapord-*.jar
